global:
  wg:
    table: "off"
    persistent_keepalive: "25"
    allowed_ips: "0.0.0.0/0, ::/0"
  bgp:
    asn: 4242421869
  community_lists:
    - name: DN42-EUROPE
      seq: 5
      value: "64511:41"
    - name: DN42-GB
      seq: 5
      value: "64511:1826"
    - name: DN42-DE
      seq: 5
      value: "64511:1276"
  as_path_acls:
    - name: AS_PATH_LEN_1
      seq: 5
      value: ^[0-9]+$

nodes:
  - name: lhr-r001
    fqdn: uk-lon3.usman.network
    wg_privkey: ***REMOVED***
    wg_pubkey: +qJnOwEDYwCbI6k89dCf006IO8Ni+ktnov/il8j+BhM=
    dn42_region: "Europe"
    iso_3166_country_code: "GB"
    bgp_large_community: "4242421869:100:1"
  - name: lhr-r002
    fqdn: uk-lon3.usman.network
    wg_privkey:
    wg_pubkey: 
    dn42_region: "Europe"
    iso_3166_country_code: "GB"
    bgp_large_community: "4242421869:100:2"

mesh:
  - name: lhr-r001
    loopback: 172.22.132.161
  - name: lhr-r002
    loopback: 172.22.132.162

peers:
  lhr-r001:
    - name: KIOUBIT
      wg_pubkey: sLbzTRr2gfLFb24NPzDOpy8j09Y6zI+a7NkeVMdVSR8=
      wg_endpoint: 192.29.101.166:21869
      wg_address: fe80::ade1
      wg_listenport: auto
      asn: "4242423914"
      peer_address: fe80::ade0
      latency_us: "13700"
      dn42_region: "Europe"
      iso_3166_country_code: GB
    - name: LARE
      wg_pubkey: RJaU1kRfiOREvKihiDMFpNrEGpN8td3z+UvHxabOlR0=
      wg_endpoint: uk01.dn42.lare.cc:21869
      wg_address: fe80::ade1/64
      wg_listenport: auto
      asn: "4242423035"
      peer_address: fe80::3035:138
      latency_us: "50000"
      dn42_region: "Europe"
      iso_3166_country_code: GB
    - name: EXPLORO
      wg_pubkey: lPjxQWE61Gvksk+KzecfZumr9SArDef3TGvAWXjCDD0=
      wg_endpoint: frank1.exploro.one:32639
      # wg_address: fe80::1771/64
      wg_listenport: auto
      asn: "4242421771"
      peer_address: fe80::da7a:a0ef:5a4b:89bc
      latency_us: "29000"
      dn42_region: "Europe"
      iso_3166_country_code: DE
    # - name: C4TG1RL5
    #   wg_pubkey: 
    #   wg_endpoint: 
    #   # wg_address: fe80::1441/64
    #   wg_listenport: auto
    #   asn: "4242421441"
    #   peer_address: 
    #   latency_us: "400"
    #   dn42_region: "Europe"
    #   iso_3166_country_code: DE
    - name: ROUTEDBITS
      wg_pubkey: vlqNoUSJ4T2sORBHusdwr9rCtQfdsIJvjV3Y/qBUcgY=
      wg_endpoint: router.lon1.routedbits.com:51869 
      wg_address: fe80::2070/64
      wg_listenport: auto
      asn: "4242420207"
      peer_address: fe80::207
      latency_us: "16000"
      dn42_region: "Europe"
      iso_3166_country_code: GB
