$ANSIBLE_VAULT;1.1;AES256
38326331333665376433646136386232653764376635343262306666636434383031343366643636
3139643362643132663239343532643533393065316535620a326662656561643936353666326532
30366365623931396131343734313964303966363762663932396565653161333365633761323437
3265626533353431640a336432306638306432306632616263623765656463623566613139363730
63336366376231313737383962343563646361633663613439363032356564666131636665316334
62663065366530383536623336393065323831633432646366383335623665393331323630323761
32313037383939613339643062623565633330313933636230396636633165316634326234396462
35393563343965363939383965613739376538363537616665393563383238366332616237623865
39663637616236633662633135353035333138323538303965643466373934336332383937616431
39366539663734633733643838393761323938316661386438653866313231663735616638343930
39393962643461653333613461633037396130643461663464646632626332626364383433396535
34623866636265636533336666373532383063613861616633363735613365616362623032376138
30376436356162346462643264396134636237323631323832343133373034333566353934346230
30633361656161383361303131316264313434306665333266356331343832343961303434343561
31326330666437623664633265303437613766303763376537306435613666373433363734323962
66663965653336336363323139616430663864633339653631613532643033613331313166396237
36653735316232356633313230346335623630363865636538333461653130383764643830333634
65376133396136306461353230636537663061346339643461626465613531643366336538333539
35336230623562343931396262383264373163356564663934653032386633353436313333306262
34653864333432626334613162333036303863383365343331626530663035343762323061396135
6230
