$ANSIBLE_VAULT;1.1;AES256
35613661616538373063396566323262343937663935363937336365656665343238643865396438
6363393537666333393738663435386365373165663462640a396336323231336536656132636439
63343965366461346161313563346437616332383336653939386134323566363364383964616364
6431666463616435660a636336376438646538333139353266306439396636373639353731626334
30373266373339626339393735333436373162623338336166306138656631626637303965366430
61653636306333303937336439303237666461653236376461323930623562613238656434393933
33343235653962366266666264393965373966333866306535363137623865356435383135343136
66346264393931643163643534386434336336346336333634353731386161356637643234303035
66653163643066333439353364343262656333323463636234653166383732333865393535306266
36623365663738323566383663373636343130383866656634376133666663393234623862623138
61353639393063386633353938666639326632633537613364383162353531326239323534646463
35376533336531643233643236333430643761393462353465346166346136323163376437653062
35623864363463643135373234326137373332343664646466353637323436623366
