$ANSIBLE_VAULT;1.1;AES256
36346663643237343361346331393064656165353661636330646535336338653131343465373733
3464666165383862343264326363656364643336353966340a363036356639613538643637393535
66383632376538353632383837353932653236396461333635363330356133383165663463366262
3337393563383161650a363663366533613733663465333039306637356532626632393434636166
30366462613130343361653233336430303236623063376466376539316632316464346130336164
31623162363838393064623166656237303931633462303533323332373136393833336162633362
39373730366362613735626336326436666431656134336233356361393538633865333931336135
39316665623231376535613134303166663262626436386666653334323938393537393539316238
30336238353164336632303162383036653032323634373537343965616532653538653566343064
39306161383761356564646134366366396364323438623731643563393034366366623465636238
62623663623630353335663964623530336436353062653435626463386364393931613834303532
30356438643763363232366661613530333434623263313264613039316230663631346439343965
64663466653533656330373066323634356235373264313039303032353366633037
