---
# FRR handlers

- name: restart frr
  systemd:
    name: frr
    state: restarted

- name: reload frr config
  shell: |
    vtysh -f /etc/frr/frr.conf
  # Note: This applies the new configuration from frr.conf
