---
# FRR handlers

- name: restart frr
  when: not ansible_check_mode
  systemd:
    name: frr
    state: restarted

- name: reload frr config
  when: not ansible_check_mode
  systemd:
    name: frr
    state: restarted
  # Note: FRR must be restarted to fully replace config (vtysh -f merges instead of replacing)
